version: '3'

services:
  ngx:
    image: 'nginx:alpine'
    container_name: 'sesami-ngx'
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - sesami
      - redis
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-sesami'
    environment:
      POSTGRES_PASSWORD: 'postgres_sesami'
      POSTGRES_USER: 'postgres_sesami'
      POSTGRES_DB: 'sesami'
    volumes:
      - /mnt/db:/var/lib/postgresql/data
    restart: always
    command: '-p 8081'
    ports:
      - '8081:8081'

  redis:
    image: 'bitnami/redis:latest'
    container_name: 'sesami-redis'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    deploy:
      resources:
        limits:
          memory: 500M

  sesami:
    image: sesami
    container_name: sesami
    build:
      context: .
      dockerfile: deploy/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
    entrypoint: ['npm', 'run', 'cluster']
    restart: always
